name: Sample-FPL

on:
  workflow_dispatch:
    inputs:
      GW:
        description: 'GW Number'
        required: true

jobs:
  build-and-run:
    name: Sample values from FPL
    runs-on: ubuntu-latest

    steps:
      - name: Check current directory
        run: pwd
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout webpage branch
        uses: actions/checkout@v2
        with:
          ref: 'webpage'
          path: ./src/build
      - name: Make sure data folder exists
        run: mkdir -p ./src/build/sample
      - name: Pull docker image
        run: docker pull sertalpbilal/selenium_docker:latest
      - name: Run docker image
        run: |
          if [ ${{ github.event.inputs.GW }} == 'season' ]; then
            docker run -t --rm -e LANG=C.UTF-8 -v $(pwd):/app sertalpbilal/selenium_docker bash -c "cd /app/scripts && python3 -m pip install -r requirements.txt && cd /app/src && python3 -c \"import collect; collect.sample_all_season()\" "
          else
            docker run -t --rm -e LANG=C.UTF-8 -e GW=${{ github.event.inputs.GW }} -v $(pwd):/app sertalpbilal/selenium_docker bash -c "cd /app/scripts && python3 -m pip install -r requirements.txt && chmod +x *.sh && ./sample.sh"
          fi
        shell: bash
      - name: Add changes to the branch
        run: |
          cd src/build
          git add -u
          git add .
          git config user.name "Github Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Automated build - Data Sample GW${{ github.event.inputs.GW }} $GITHUB_RUN_ID"
          git push
